using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MongoDB.Driver;
using SessionFlow.Desktop.Data;
using SessionFlow.Desktop.Models;
using StackExchange.Redis;
using System.IO;
using System.Net.Http;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace SessionFlow.Desktop.Services;

// ── Provider Abstraction ──────────────────────────────────────────────────────
public interface IChatCompletionProvider
{
    IAsyncEnumerable<string> StreamAsync(string prompt, List<AIChatMessage> history, CancellationToken ct);
    string ModelName { get; }
}

// ── Smart Mock Provider (production-safe, no external API key needed) ─────────
public class SmartMockProvider : IChatCompletionProvider
{
    public string ModelName => "mock-v1";

    public async IAsyncEnumerable<string> StreamAsync(
        string prompt,
        List<AIChatMessage> history,
        [EnumeratorCancellation] CancellationToken ct)
    {
        var responses = new[]
        {
            $"Analyzing your request: **\"{TruncatePrompt(prompt)}\"**\n\n",
            "Based on the platform data available, here's my assessment:\n\n",
            BuildContextualResponse(prompt),
            "\n\n---\n*AI response generated by SessionFlow Neural Engine (Mock Mode)*"
        };

        foreach (var chunk in responses)
        {
            ct.ThrowIfCancellationRequested();
            await Task.Delay(80, ct);
            yield return chunk;
        }
    }

    private static string TruncatePrompt(string prompt) =>
        prompt.Length > 60 ? prompt[..60] + "..." : prompt;

    private static string BuildContextualResponse(string prompt)
    {
        var lower = prompt.ToLowerInvariant();
        if (lower.Contains("session") || lower.Contains("attendance"))
            return "📊 **Session & Attendance Insights:**\n- Track session completion rates via the Analytics dashboard\n- Use the Session Timeline to identify patterns in student engagement\n- Automated reminders are sent 30 mins before each session";
        if (lower.Contains("student"))
            return "👥 **Student Management Tips:**\n- Use bulk enrollment for faster onboarding\n- Student performance scores update after each session\n- Export reports in CSV/PDF from the Reporting module";
        if (lower.Contains("broadcast") || lower.Contains("message"))
            return "📣 **Broadcast System:**\n- You can target by role: Admin, Engineer, or Student\n- Scheduled broadcasts support future-dated delivery\n- Track open rates in Broadcast History";
        if (lower.Contains("report") || lower.Contains("analytics"))
            return "📈 **Analytics Overview:**\n- DAU/WAU/MAU trends are tracked automatically\n- Feature engagement shows which pages users visit most\n- Session metrics include average duration and peak hours";
        return "✅ I'm here to help with platform management, session tracking, analytics, and user insights. What specific data would you like to explore?";
    }
}

// ── OpenAI Provider (real implementation, activated by config) ─────────────
public class OpenAIProvider : IChatCompletionProvider
{
    private readonly string _apiKey;
    private readonly string _model;
    private readonly HttpClient _http;
    public string ModelName => _model;

    public OpenAIProvider(HttpClient http, string apiKey, string model = "gpt-4o-mini")
    {
        _http = http;
        _apiKey = apiKey;
        _model = model;
    }

    public async IAsyncEnumerable<string> StreamAsync(
        string prompt,
        List<AIChatMessage> history,
        [EnumeratorCancellation] CancellationToken ct)
    {
        // Build message array
        var messages = new List<object>
        {
            new { role = "system", content = "You are a helpful AI assistant for SessionFlow, an educational SaaS platform. Be concise, professional, and helpful." }
        };
        foreach (var h in history.TakeLast(10))
            messages.Add(new { role = h.Role, content = h.Content });
        messages.Add(new { role = "user", content = prompt });

        var body = JsonSerializer.Serialize(new
        {
            model = _model,
            messages,
            stream = true,
            max_tokens = 1024
        });

        using var req = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/chat/completions");
        req.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _apiKey);
        req.Content = new StringContent(body, Encoding.UTF8, "application/json");

        using var resp = await _http.SendAsync(req, HttpCompletionOption.ResponseHeadersRead, ct);
        resp.EnsureSuccessStatusCode();

        using var stream = await resp.Content.ReadAsStreamAsync(ct);
        using var reader = new StreamReader(stream);

        while (!reader.EndOfStream && !ct.IsCancellationRequested)
        {
            var line = await reader.ReadLineAsync(ct);
            if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;
            var data = line["data: ".Length..];
            if (data == "[DONE]") break;

            JsonDocument? doc = null;
            try { doc = JsonDocument.Parse(data); } catch { continue; }
            using (doc)
            {
                var content = doc.RootElement
                    .GetProperty("choices")[0]
                    .GetProperty("delta")
                    .TryGetProperty("content", out var c) ? c.GetString() : null;
                if (content != null) yield return content;
            }
        }
    }
}

// ── Groq Provider (100% FREE — no credit card, OpenAI-compatible) ─────────
// Sign up at https://console.groq.com → get API key → set GROQ_API_KEY env var.
// Uses Llama 3.3 70B (strongest free model) with ~500 tokens/sec inference.
// Free tier: ~30 RPM, ~14,400 RPD — more than enough for SaaS usage.
public class GroqProvider : IChatCompletionProvider
{
    private readonly string _apiKey;
    private readonly string _model;
    private readonly HttpClient _http;
    public string ModelName => $"groq/{_model}";

    private const string SystemPrompt = """
        You are SessionFlow Code Assistant — an expert coding AI embedded inside SessionFlow.
        You specialize in helping developers write, debug, and understand code.

        STRICT RULES:
        - You ONLY help with coding, programming, and technical questions.
        - If asked about non-coding topics, politely redirect: "I'm a coding assistant. Ask me about code!"
        - ALWAYS wrap code in fenced markdown code blocks with the language tag, e.g. ```csharp ... ```
        - When showing multiple files or steps, use separate code blocks for each.
        - Explain code concisely — keep explanations short and actionable.
        - Use bullet points for multi-step explanations.
        - Supported languages include but are not limited to: C#, TypeScript, JavaScript, Python, SQL, HTML, CSS, React, .NET, and more.
        - If the user asks to fix a bug, show ONLY the changed lines with context, not the entire file.
        - Keep responses under 600 words unless the user asks for detail.
        """;

    public GroqProvider(HttpClient http, string apiKey, string model = "llama-3.3-70b-versatile")
    {
        _http = http;
        _apiKey = apiKey;
        _model = model;
    }

    public async IAsyncEnumerable<string> StreamAsync(
        string prompt,
        List<AIChatMessage> history,
        [EnumeratorCancellation] CancellationToken ct)
    {
        var messages = new List<object> { new { role = "system", content = SystemPrompt } };
        foreach (var h in history.TakeLast(10))
            messages.Add(new { role = h.Role, content = h.Content });
        messages.Add(new { role = "user", content = prompt });

        var body = JsonSerializer.Serialize(new
        {
            model = _model,
            messages,
            stream = true,
            max_tokens = 1024,
            temperature = 0.7
        });

        using var req = new HttpRequestMessage(HttpMethod.Post, "https://api.groq.com/openai/v1/chat/completions");
        req.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _apiKey);
        req.Content = new StringContent(body, Encoding.UTF8, "application/json");

        using var resp = await _http.SendAsync(req, HttpCompletionOption.ResponseHeadersRead, ct);
        resp.EnsureSuccessStatusCode();

        using var stream = await resp.Content.ReadAsStreamAsync(ct);
        using var reader = new StreamReader(stream);

        while (!reader.EndOfStream && !ct.IsCancellationRequested)
        {
            var line = await reader.ReadLineAsync(ct);
            if (string.IsNullOrEmpty(line) || !line.StartsWith("data: ")) continue;
            var data = line["data: ".Length..];
            if (data == "[DONE]") break;

            JsonDocument? doc = null;
            try { doc = JsonDocument.Parse(data); } catch { continue; }
            using (doc)
            {
                var content = doc.RootElement
                    .GetProperty("choices")[0]
                    .GetProperty("delta")
                    .TryGetProperty("content", out var c) ? c.GetString() : null;
                if (content != null) yield return content;
            }
        }
    }
}

// ── Main AI Service ───────────────────────────────────────────────────────────
public class AIService
{
    private readonly IChatCompletionProvider _provider;
    private readonly MongoService _db;
    private readonly IConnectionMultiplexer? _redis;
    private readonly ILogger<AIService> _logger;
    private readonly IConfiguration _config;

    // Quota per tier (requests per 3-hour window)
    private const int QuotaWindowHours = 3;
    public static readonly Dictionary<string, int> TierQuotas = new()
    {
        ["Free"] = 5,
        ["Pro"] = 90,
        ["Ultra"] = 180,
        ["Enterprise"] = int.MaxValue
    };

    public AIService(
        IChatCompletionProvider provider,
        MongoService db,
        IConnectionMultiplexer? redis,
        ILogger<AIService> logger,
        IConfiguration config)
    {
        _provider = provider;
        _db = db;
        _redis = redis;
        _logger = logger;
        _config = config;
    }

    /// <summary>Check Redis cache, then call provider, then log to MongoDB.</summary>
    public async IAsyncEnumerable<string> ChatStreamAsync(
        Guid userId,
        string userRole,
        string sessionId,
        string prompt,
        List<AIChatMessage> history,
        string userTier = "Free",
        [EnumeratorCancellation] CancellationToken ct = default)
    {
        var cacheKey = BuildCacheKey(prompt, history);
        var cacheDb = _redis?.GetDatabase();

        // ── 1. Quota Check (3-hour window) ────────────────────────────────
        if (!await CheckQuotaAsync(userId, userTier, cacheDb))
        {
            yield return "⚠️ **Quota reached.** You've used all your messages for this 3-hour window. Upgrade your plan or wait for the next window.";
            yield break;
        }

        // ── 2. Cache Hit ────────────────────────────────────────────────────
        string? cached = null;
        if (cacheDb != null)
        {
            cached = await cacheDb.StringGetAsync(cacheKey);
        }

        if (!string.IsNullOrEmpty(cached))
        {
            _logger.LogDebug("[AI] Cache HIT for prompt hash {Hash}", cacheKey[^12..]);
            yield return cached;
            await LogAsync(userId, userRole, sessionId, prompt, cached, wasCached: true);
            yield break;
        }

        // ── 3. Stream from provider & accumulate ────────────────────────────
        var sb = new StringBuilder();
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var wasError = false;
        string? errorMsg = null;

        await foreach (var chunk in _provider.StreamAsync(prompt, history, ct))
        {
            sb.Append(chunk);
            yield return chunk;
        }

        sw.Stop();
        var fullResponse = sb.ToString();

        // ── 4. Cache the response (TTL: 1 hour) ────────────────────────────
        if (cacheDb != null && !string.IsNullOrEmpty(fullResponse))
        {
            await cacheDb.StringSetAsync(cacheKey, fullResponse, TimeSpan.FromHours(1));
        }

        // ── 5. Increment quota usage (3-hour window) ─────────────────────
        if (cacheDb != null)
        {
            var (quotaKey, ttl) = BuildQuotaKey(userId);
            await cacheDb.StringIncrementAsync(quotaKey);
            await cacheDb.KeyExpireAsync(quotaKey, ttl);
        }

        // ── 6. Persist log to MongoDB ───────────────────────────────────────
        await LogAsync(userId, userRole, sessionId, prompt, fullResponse,
            durationMs: (int)sw.ElapsedMilliseconds,
            wasCached: false, wasError: wasError, errorMessage: errorMsg);
    }

    private async Task<bool> CheckQuotaAsync(Guid userId, string tier, IDatabase? db)
    {
        if (db == null) return true;
        var limit = TierQuotas.GetValueOrDefault(tier, 5);
        if (limit == int.MaxValue) return true;

        var (quotaKey, _) = BuildQuotaKey(userId);
        var current = (long?)await db.StringGetAsync(quotaKey) ?? 0;
        return current < limit;
    }

    /// <summary>Builds a Redis key scoped to a 3-hour bucket from Unix epoch.</summary>
    private static (string key, TimeSpan ttl) BuildQuotaKey(Guid userId)
    {
        var now = DateTimeOffset.UtcNow;
        var bucket = now.ToUnixTimeSeconds() / (QuotaWindowHours * 3600);
        var key = $"ai:quota:{userId}:{bucket}";
        // TTL = time remaining until this 3h window ends
        var windowStart = DateTimeOffset.FromUnixTimeSeconds(bucket * QuotaWindowHours * 3600);
        var windowEnd = windowStart.AddHours(QuotaWindowHours);
        var ttl = windowEnd - now;
        if (ttl < TimeSpan.FromSeconds(10)) ttl = TimeSpan.FromHours(QuotaWindowHours);
        return (key, ttl);
    }

    private async Task LogAsync(
        Guid userId, string userRole, string sessionId,
        string prompt, string response,
        int durationMs = 0, bool wasCached = false,
        bool wasError = false, string? errorMessage = null)
    {
        try
        {
            var log = new AILog
            {
                UserId = userId,
                UserName = userRole,
                SessionId = sessionId,
                Prompt = prompt,
                Response = response,
                Model = _provider.ModelName,
                DurationMs = durationMs,
                WasCached = wasCached,
                WasError = wasError,
                ErrorMessage = errorMessage
            };
            await _db.AILogs.InsertOneAsync(log);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "[AI] Failed to persist AI log");
        }
    }

    // ── Prompt Preset Management ─────────────────────────────────────────────
    public async Task<List<AIPromptPreset>> GetPresetsAsync(Guid userId)
    {
        var filter = Builders<AIPromptPreset>.Filter.Or(
            Builders<AIPromptPreset>.Filter.Eq(p => p.UserId, userId),
            Builders<AIPromptPreset>.Filter.Eq(p => p.IsSystemPreset, true)
        );
        return await _db.AIPromptPresets.Find(filter)
            .SortByDescending(p => p.UsageCount)
            .ToListAsync();
    }

    public async Task<AIPromptPreset> CreatePresetAsync(Guid userId, AIPresetRequest req)
    {
        var preset = new AIPromptPreset
        {
            UserId = userId,
            Title = req.Title,
            Prompt = req.Prompt,
            Icon = req.Icon,
            Category = req.Category
        };
        await _db.AIPromptPresets.InsertOneAsync(preset);
        return preset;
    }

    public async Task DeletePresetAsync(Guid presetId, Guid userId)
    {
        await _db.AIPromptPresets.DeleteOneAsync(
            p => p.Id == presetId && p.UserId == userId && !p.IsSystemPreset);
    }

    public async Task<List<AILog>> GetLogsAsync(Guid? userId, int page = 1, int pageSize = 50)
    {
        var filter = userId.HasValue
            ? Builders<AILog>.Filter.Eq(l => l.UserId, userId.Value)
            : Builders<AILog>.Filter.Empty;

        return await _db.AILogs.Find(filter)
            .SortByDescending(l => l.Timestamp)
            .Skip((page - 1) * pageSize)
            .Limit(pageSize)
            .ToListAsync();
    }

    /// <summary>Returns real-time quota info for the current 3-hour window.</summary>
    public async Task<(int used, int limit, DateTimeOffset resetsAt)> GetQuotaInfoAsync(Guid userId, string tier, IDatabase? cacheDb)
    {
        var limit = TierQuotas.GetValueOrDefault(tier, 5);
        if (cacheDb == null) return (0, limit, DateTimeOffset.UtcNow.AddHours(QuotaWindowHours));

        var (quotaKey, _) = BuildQuotaKey(userId);
        var used = (int)((long?)await cacheDb.StringGetAsync(quotaKey) ?? 0);

        // Calculate when this window resets
        var now = DateTimeOffset.UtcNow;
        var bucket = now.ToUnixTimeSeconds() / (QuotaWindowHours * 3600);
        var windowEnd = DateTimeOffset.FromUnixTimeSeconds((bucket + 1) * QuotaWindowHours * 3600);

        return (used, limit, windowEnd);
    }

    /// <summary>Returns user's AI chat history from MongoDB, grouped by session.</summary>
    public async Task<List<AILog>> GetUserHistoryAsync(Guid userId, int limit = 100)
    {
        return await _db.AILogs.Find(
            Builders<AILog>.Filter.Eq(l => l.UserId, userId)
        )
        .SortByDescending(l => l.Timestamp)
        .Limit(limit)
        .ToListAsync();
    }

    private static string BuildCacheKey(string prompt, List<AIChatMessage> history)
    {
        var historyContext = string.Join("|", history.TakeLast(3).Select(h => $"{h.Role}:{h.Content[..Math.Min(50, h.Content.Length)]}"));
        var raw = $"{prompt.Trim()}___{historyContext}";
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(raw));
        return $"ai:cache:{Convert.ToHexString(hash)[..32].ToLower()}";
    }
}
