using Microsoft.AspNetCore.Http;
using Serilog.Context;

namespace SessionFlow.Desktop.Api.Middleware;

/// <summary>
/// O2: Correlation ID Middleware — ensures every request has a unique correlation ID.
/// 
/// Flow:
///   1. Reads incoming X-Correlation-Id header (if client sent one)
///   2. Falls back to HttpContext.TraceIdentifier (auto-generated by Kestrel)
///   3. Pushes "CorrelationId" into Serilog LogContext for all downstream log entries
///   4. Sets the response header so clients can trace requests
///
/// This enables end-to-end request tracing across frontend → backend → database.
/// </summary>
public class CorrelationIdMiddleware
{
    private const string HeaderName = "X-Correlation-Id";
    private readonly RequestDelegate _next;

    public CorrelationIdMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        // Use incoming header if provided, otherwise use Kestrel's trace ID
        var correlationId = context.Request.Headers[HeaderName].FirstOrDefault()
                            ?? context.TraceIdentifier;

        // Overwrite TraceIdentifier for consistent downstream usage
        context.TraceIdentifier = correlationId;

        // Set response header so clients can reference the same ID
        context.Response.OnStarting(() =>
        {
            context.Response.Headers[HeaderName] = correlationId;
            return Task.CompletedTask;
        });

        // Push into Serilog LogContext — all logs in this request scope will include it
        using (LogContext.PushProperty("CorrelationId", correlationId))
        using (LogContext.PushProperty("RequestPath", context.Request.Path.Value))
        using (LogContext.PushProperty("RequestMethod", context.Request.Method))
        {
            // Also push UserId if authenticated
            var userId = context.User?.FindFirst("sub")?.Value
                         ?? context.User?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            
            if (!string.IsNullOrEmpty(userId))
            {
                using (LogContext.PushProperty("UserId", userId))
                {
                    await _next(context);
                }
            }
            else
            {
                await _next(context);
            }
        }
    }
}
